[package]
name = "schemerz-rusqlite"
version = "0.0.0"
edition = "2021"
rust-version = "1.59"
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Kris Nuttycombe <kris@electriccoin.co>",
]
description = "SQLite3 adapter for the Schemerz database schema migration library "
readme = "../README.md"
keywords = ["database", "migration", "sqlite", "sql"]
categories = ["database"]
license = "MIT/Apache-2.0"
repository = "https://github.com/zcash/schemerz"

[dependencies]
uuid = { version = "1" }
rusqlite = "0.29.0"

schemerz = { version = "0.0", path = "../schemerz" }
